Microsoft/EmbeddedSocial-iOS-SDK

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial.xcworkspace/contents.xcworkspacedata, EmbeddedSocialUITests/APIMock/APIRouter.swift, EmbeddedSocialUITests/Tests/Loop.swift, EmbeddedSocialUITests/Tests/TestHome.swift, EmbeddedSocialUITests/Tests/TestMyPins.swift
=> My pins ui test

EmbeddedSocial/Sources/Model/Auth/TwitterServerBasedAPI.swift, EmbeddedSocial/Sources/Model/Auth/TwitterWebBasedAPI.swift, EmbeddedSocial/Vendor/OAuthSwift/Sources/OAuth1Swift.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/407 implemented
=> #407 - The "processing" spinner is displayed on "Sign In" screen after cancellation of sign in process via Twitter - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/Auth/FacebookAPI.swift, EmbeddedSocial/Sources/Model/RequestExecutionStrategy/SuggestedUsersRequestExecutionStrategy.swift, EmbeddedSocial/Sources/Model/Services/SocialService.swift, EmbeddedSocial/Sources/Modules/Following/Presenter/FollowingPresenter.swift, EmbeddedSocial/Sources/Modules/Following/Router/FollowingRouter.swift, EmbeddedSocial/Sources/Modules/Following/Router/FollowingRouterInput.swift, EmbeddedSocial/Sources/Modules/SearchPeople/Configurator/SearchPeopleConfigurator.swift, EmbeddedSocial/Sources/Modules/SuggestedUsers/APIs/SuggestedUsersAPI.swift, EmbeddedSocial/Sources/Modules/SuggestedUsers/Configurator/SuggestedUsersConfigurator.swift, EmbeddedSocialTests/Mocks/MockSocialService.swift, EmbeddedSocialTests/Modules/SuggestedUsers/SuggestedUsersAPITests.swift, EmbeddedSocialTests/ServicesTests/FeedCacheTests.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/387 - implemented.
Also fixed autolayout crash on SuggestedUsers screen.
=> #387 - Suggested Users: updated FB settings to ask for more permissions

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Controls/PostCells/PostCell.swift, EmbeddedSocial/Sources/Controls/PostCells/PostCell.xib
=> Fixed cell text size.

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Modules/PostMenuModule/Presenter/PostMenuModulePresenter.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/442 implemented
=> #442 - [Manual] - No "Sign In" screen when not signed in user tries to follow other user - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListPresenter.swift, EmbeddedSocial/Sources/Modules/UserProfile/Presenter/UserProfilePresenter.swift, EmbeddedSocialTests/Modules/Activity/ActivityDataSourceTests.swift, EmbeddedSocialTests/Modules/UserList/UserListPresenterTests.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/444 implemented
=> #444 - [Manual] - No "Sign In" screen for some operation on "Profile" screen for not signed in user - Implemented

EmbeddedSocial/Sources/Modules/UserProfile/Presenter/UserProfilePresenter.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/452 implemented
=> #452 - [Manual] - The "followers" counter increases after every tapping on "Following" button - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Extensions/UINavigationBar+Ext.swift, EmbeddedSocial/Sources/Modules/CreatePost/View/CreatePost.storyboard, EmbeddedSocial/Sources/Modules/CreatePost/View/CreatePostViewController.swift, EmbeddedSocial/Sources/Modules/UserProfile/Presenter/UserProfilePresenter.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/455 implemented
=> #455 - [Manual] - Color of elements is changed after adding of a new post - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/CrossModuleCoordinator.swift, EmbeddedSocial/Sources/Modules/Activity/Entities/ActivityEntities.swift, EmbeddedSocialTests/Mocks/MockTopicServices.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/464 implemented
=> #464 - [Manual] - Search criteria and search results are not cleared after user was signed out - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Modules/UserProfile/Presenter/UserProfilePresenter.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/472 implemented
=>  #472 - [Manual] - Tabs are disabled after switching between them in offline mode - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/RequestExecutionStrategy/RequestExecutorProvider.swift, EmbeddedSocial/Sources/Model/ResponseProcessors/MyRecentTopicsFeedResponseProcessor.swift, EmbeddedSocial/Sources/Model/ResponseProcessors/TopicsFeedResponseProcessor.swift, EmbeddedSocial/Sources/Model/Services/TopicService.swift, EmbeddedSocialTests/ModelTests/ResponseProcessors/MyRecentTopicsFeedResponseProcessorTests.swift, EmbeddedSocialTests/ModelTests/ResponseProcessors/TopicsFeedResponseProcessorTests.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/510 - implemented
=> #510 - [Feed]: Display topics created from offline only in author's recent feed - Implemented

EmbeddedSocial/Sources/Modules/FeedModule/View/FeedModuleViewController.swift
Possible workaround for crash on iOS 10.
=> Possible workaround for crash on ios10.

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/Cache/Commands/CommentCommands/CommentCommand.swift, EmbeddedSocial/Sources/Model/Cache/Commands/CommentCommands/CreateCommentCommand.swift, EmbeddedSocial/Sources/Model/Cache/Commands/TopicCommands/TopicCommand.swift, EmbeddedSocial/Sources/Model/Cache/Commands/TopicsFeedApplicableCommand.swift, EmbeddedSocial/Sources/Model/Cache/PredicateBuilder.swift, EmbeddedSocial/Sources/Model/ResponseProcessors/MyRecentTopicsFeedResponseProcessor.swift, EmbeddedSocial/Sources/Model/ResponseProcessors/SearchTopicsFeedResponseProcessor.swift, EmbeddedSocial/Sources/Model/ResponseProcessors/TopicsFeedResponseProcessor.swift, EmbeddedSocialTests/Mocks/MockTopicServicePredicateBuilder.swift, EmbeddedSocialTests/ModelTests/CommentCommands/CreateCommentCommandTests.swift, EmbeddedSocialTests/ModelTests/ResponseProcessors/TopicsFeedResponseProcessorTests.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/493 - implemented
=> #493 - [Manual] - Counter for comments does not changing in offline mode - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/Cache/Operations/CommentCommandsOperations/CreateCommentOperation.swift, EmbeddedSocial/Sources/Model/Cache/Operations/ReplyCommandsOperations/CreateReplyOperation.swift, EmbeddedSocial/Sources/Model/Services/Comments/CommentsService.swift, EmbeddedSocial/Sources/Utils/OutgoingCommandsRelatedHandleUpdater.swift, EmbeddedSocialTests/Mocks/MockCommentService.swift, EmbeddedSocialTests/Mocks/MockRelatedHandleUpdater.swift, EmbeddedSocialTests/ModelTests/CommentOperations/CreateCommentOperationTests.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/515 implemented
=> #515 - [Manual] - Comment that was added in offline disappears after pull to refresh operation - Implemented

EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListPresenter.swift, EmbeddedSocialTests/Modules/UserList/UserListPresenterTests.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/517 - implemented
=> #517 - going to search forces user to sign in - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Resources/Localizable.strings, EmbeddedSocial/Sources/Controls/ProfileSummaryView/ProfileSummaryView.xib, EmbeddedSocial/Sources/Generated/SwiftGen/Strings.swift, EmbeddedSocial/Sources/Model/Entities/User.swift, EmbeddedSocial/Sources/Model/SocialPlus/SocialPlus.swift, EmbeddedSocial/Sources/Modules/UserProfile/Presenter/UserProfilePresenter.swift, EmbeddedSocial/Sources/Modules/UserProfile/View/PrivateUserProfileView.swift, EmbeddedSocial/Sources/Modules/UserProfile/View/UserProfile.storyboard, EmbeddedSocial/Sources/Modules/UserProfile/View/UserProfileViewController.swift, EmbeddedSocial/Sources/Modules/UserProfile/View/UserProfileViewInput.swift, EmbeddedSocial/Sources/Utils/Constants.swift, EmbeddedSocialTests/ModelTests/ResponseProcessors/MyRecentTopicsFeedResponseProcessorTests.swift, EmbeddedSocialTests/ModelTests/ResponseProcessors/SearchTopicsFeedResponseProcessorTests.swift, EmbeddedSocialTests/Modules/UserProfile/Mocks/MockUserProfileView.swift, EmbeddedSocialTests/Modules/UserProfile/UserProfilePresenterTests.swift
https://github.com/Microsoft/EmbeddedSocial-iOS-SDK/issues/548 - implemented
=> #548 - Profile: Need to hide posts for private user

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Resources/Localizable.strings, EmbeddedSocial/Sources/Common/APIError.swift, EmbeddedSocial/Sources/Extensions/UIViewController+Alerts.swift, EmbeddedSocial/Sources/Generated/SwiftGen/Strings.swift, EmbeddedSocialTests/UtilsTest/APIErrorTests.swift
=> #550 - Profile: Open profile in offline mode show an error - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Controls/PostCells/PostCell.swift, EmbeddedSocial/Sources/Controls/PostCells/PostCell.xib, EmbeddedSocial/Sources/Controls/PostFeedLabel.swift, EmbeddedSocial/Sources/Extensions/PostCell+Themeable.swift, EmbeddedSocial/Sources/Model/Entities/Post.swift, EmbeddedSocial/Sources/Modules/FeedModule/Presenter/FeedModulePresenter.swift, EmbeddedSocial/Sources/Modules/FeedModule/Router/FeedModuleRouter.swift, EmbeddedSocial/Sources/Modules/FeedModule/View/FeedModuleViewController.swift, EmbeddedSocial/Sources/Utils/Constants.swift, EmbeddedSocial/Sources/Utils/SearchScreenOpener.swift, Podfile
=> New label added.

EmbeddedSocial-Example/AppDelegate.swift, EmbeddedSocial-Example/GoogleService-Info.plist, EmbeddedSocial-Example/Info.plist, EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Utils/ThirdPartyConfigurator.swift
1. #585 implemented.
2. Disabled HockeyApp version check for iOS Simulator.
=> #585 - Sign-in: Need to update bundle id in google.plist to support latest changes in the bundle name - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Common/Base/BaseNavigationViewController.swift, EmbeddedSocial/Sources/Controls/ProfileSummaryView/ProfileSummaryView.xib, EmbeddedSocial/Sources/Modules/Login/View/Login.storyboard, EmbeddedSocial/Sources/Modules/Search/View/Search.storyboard, EmbeddedSocial/Sources/Modules/Search/View/SearchViewController.swift, EmbeddedSocial/Sources/Utils/Constants.swift
#536 - Partially implemented
1. Fixed search navigation bar layout
2. Fixed Login screen for iPhone 5, iPad 9.7 inch
3. Fixed Profile screen for iPhone 5, iPad 9.7 inch
=> #536 - UI: Need to check auto-layouts (and fix if necessary) on iPad and other devices with different screen - Partially implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Extensions/NSLock+Ext.swift, EmbeddedSocial/Sources/Extensions/UICollectionView+Ext.swift, EmbeddedSocial/Sources/Extensions/UITableView+Ext.swift, EmbeddedSocial/Sources/Model/Cache/Cache.swift, EmbeddedSocial/Sources/Model/Cache/CacheType.swift, EmbeddedSocial/Sources/Model/Cache/Commands/NotificationCommands/UpdateNotificationsStatusCommand.swift, EmbeddedSocial/Sources/Model/Cache/Commands/OutgoingCommand.swift, EmbeddedSocial/Sources/Model/Cache/Operations/NotificationOperations/UpdateNotificationsStatusOperation.swift, EmbeddedSocial/Sources/Model/Cache/OutgoingCommandOperationsBuilder.swift, EmbeddedSocial/Sources/Model/Cache/PredicateBuilder.swift, EmbeddedSocial/Sources/Model/Cache/Uploader/OutgoingCommandsUploadStrategy.swift, EmbeddedSocial/Sources/Model/Services/ActivityNotificationsService.swift, EmbeddedSocial/Sources/Model/Services/Comments/CommentsService.swift, EmbeddedSocial/Sources/Model/Services/Replies/RepliesService.swift, EmbeddedSocial/Sources/Model/SocialPlus/SocialPlus.swift, EmbeddedSocial/Sources/Utils/Reusable.swift, EmbeddedSocialTests/Mocks/MockOutgoingCommandsPredicateBuilder.swift, EmbeddedSocialTests/ModelTests/NotificationCommands/UpdateNotificationsStatusCommandTests.swift, EmbeddedSocialTests/ModelTests/NotificationOperations/UpdateNotificationsStatusOperationTests.swift, EmbeddedSocialTests/ModelTests/OutgoingCommandOperationsBuilderTests.swift, EmbeddedSocialTests/ModelTests/OutgoingCommandsUploadStrategyTests.swift
=> #591 - Activity: cache update notifications status outgoing request - Implemented

EmbeddedSocial/Sources/Controls/PostCells/PostCell.swift, EmbeddedSocial/Sources/Modules/FeedModule/View/FeedModule.storyboard
Fix for embedded feed module.
#616 - due to nature of PostDetailtPresenter layout - post cell needs minimal height.
#402 - fixed embedded feed module collectionView => wrong top constraint behavior.
=> Added minimal height for image. Fix #616 + #402

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/Cache/Operations/CommentCommandsOperations/CreateCommentOperation.swift, EmbeddedSocial/Sources/Model/Services/Comments/CommentsService.swift, EmbeddedSocial/Sources/Model/Services/Replies/RepliesService.swift, EmbeddedSocial/Sources/Model/SocialPlus/DaemonsController.swift, EmbeddedSocialTests/UtilsTest/OperationQueueTests.swift
=> #614 - [Manual] - Duplication of comments\replies that were added in offline mode

EmbeddedSocial/Sources/Modules/Login/View/Login.storyboard
=> #640 - re-order authentication providers on sign-in screen - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Resources/Localizable.strings, EmbeddedSocial/Sources/Extensions/UIViewController+Alerts.swift, EmbeddedSocial/Sources/Generated/SwiftGen/Strings.swift, EmbeddedSocial/Sources/Model/Services/UserService.swift, EmbeddedSocial/Sources/Modules/Login/Configurator/LoginConfigurator.swift, EmbeddedSocial/Sources/Modules/Settings/Interactor/SettingsInteractor.swift, EmbeddedSocial/Sources/Modules/Settings/Interactor/SettingsInteractorInput.swift, EmbeddedSocial/Sources/Modules/Settings/Presenter/SettingsPresenter.swift, EmbeddedSocial/Sources/Modules/Settings/View/Settings.storyboard, EmbeddedSocial/Sources/Modules/Settings/View/SettingsViewController.swift, EmbeddedSocial/Sources/Modules/Settings/View/SettingsViewInput.swift, EmbeddedSocial/Sources/Modules/Settings/View/SettingsViewOutput.swift, EmbeddedSocial/Sources/Utils/GlobalApiErrorHandler.swift, EmbeddedSocialTests/Mocks/MockUserService.swift, EmbeddedSocialTests/Modules/Settings/Mocks/MockSettingsInteractor.swift, EmbeddedSocialTests/Modules/Settings/Mocks/MockSettingsView.swift, EmbeddedSocialTests/Modules/Settings/SettingsInteractorTests.swift, EmbeddedSocialTests/Modules/Settings/SettingsPresenterTests.swift
=> #623 - Add delete user functionality to settings page - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Resources/Localizable.strings, EmbeddedSocial/Sources/Controls/SearchHistory/SearchHistoryMediator.swift, EmbeddedSocial/Sources/Controls/SearchHistory/SearchHistoryStorage.swift, EmbeddedSocial/Sources/Generated/SwiftGen/Strings.swift, EmbeddedSocial/Sources/Model/MementoSerialization/KeyValueStorage.swift, EmbeddedSocial/Sources/Modules/Settings/Configurator/SettingsConfigurator.swift, EmbeddedSocial/Sources/Modules/Settings/Interactor/SettingsInteractor.swift, EmbeddedSocial/Sources/Modules/Settings/Interactor/SettingsInteractorInput.swift, EmbeddedSocial/Sources/Modules/Settings/Presenter/SettingsPresenter.swift, EmbeddedSocial/Sources/Modules/Settings/View/Settings.storyboard, EmbeddedSocial/Sources/Modules/Settings/View/SettingsViewController.swift, EmbeddedSocial/Sources/Modules/Settings/View/SettingsViewOutput.swift, EmbeddedSocialTests/ControlsTests/SearchHistory/SearchHistoryStorageTests.swift, EmbeddedSocialTests/Mocks/MockKeyValueStorage.swift, EmbeddedSocialTests/Modules/Settings/Mocks/MockSettingsInteractor.swift, EmbeddedSocialTests/Modules/Settings/SettingsInteractorTests.swift, EmbeddedSocialTests/Modules/Settings/SettingsPresenterTests.swift
=> #624 - Add delete search history option to settings - Implemented

EmbeddedSocial/Sources/Common/Base/BaseNavigationViewController.swift
=> #662 Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Controls/PostCells/PostCell.swift, EmbeddedSocial/Sources/Model/ViewModels/PostViewModel.swift
=> #664 - [Manual] - Image is not displayed for post that was added in offline mode - Implemented

EmbeddedSocial/Sources/Modules/FeedModule/View/FeedModuleViewController.swift
=> Fixed #661.

EmbeddedSocial/Sources/Controls/PostCells/PostCell.swift
=> #651 - [Manual] - No text for likes and comments counters after switching from "Gallery" view - Implemented

EmbeddedSocial/Sources/Controls/LoadMoreCell/LoadMoreCell.swift
=> #654 - Theme: Make border width on load more - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/Services/SocialService.swift, EmbeddedSocial/Sources/Modules/SearchPeople/Presenter/SearchPeoplePresenter.swift, EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListModuleInput.swift, EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListPresenter.swift, EmbeddedSocial/Sources/Utils/APIErrorHandler.swift, EmbeddedSocialTests/Mocks/MockUserListModuleInput.swift, EmbeddedSocialTests/Modules/SearchPeople/Mocks/MockSearchPeopleModuleOutput.swift, EmbeddedSocialTests/Modules/SearchPeople/SearchPeoplePresenterTests.swift
=> #678 - Implemented

EmbeddedSocial.xcodeproj/project.pbxproj, EmbeddedSocial/Sources/Model/Services/SocialService.swift, EmbeddedSocial/Sources/Modules/EditProfile/View/EditProfileViewController.swift, EmbeddedSocial/Sources/Modules/SearchPeople/Presenter/SearchPeoplePresenter.swift, EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListModuleInput.swift, EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListPresenter.swift, EmbeddedSocial/Sources/Utils/APIErrorHandler.swift, EmbeddedSocialTests/Mocks/MockUserListModuleInput.swift, EmbeddedSocialTests/Modules/SearchPeople/Mocks/MockSearchPeopleModuleOutput.swift, EmbeddedSocialTests/Modules/SearchPeople/SearchPeoplePresenterTests.swift
=> #679 - Implemented

EmbeddedSocial/Sources/Modules/Search/Presenter/SearchPresenter.swift, EmbeddedSocial/Sources/Modules/Search/View/SearchViewController.swift, EmbeddedSocial/Sources/Modules/Search/View/SearchViewInput.swift, EmbeddedSocial/Sources/Modules/SearchTopics/Presenter/SearchTopicsModuleOutput.swift, EmbeddedSocial/Sources/Modules/SearchTopics/Presenter/SearchTopicsPresenter.swift, EmbeddedSocialTests/Modules/Search/Mocks/MockSearchView.swift, EmbeddedSocialTests/Modules/Search/SearchPresenterTests.swift, EmbeddedSocialTests/Modules/SearchTopics/Mocks/MockSearchTopicsModuleOutput.swift, EmbeddedSocialTests/Modules/SearchTopics/SearchTopicsPresenterTests.swift
=> #683 implemented

EmbeddedSocial/Sources/Modules/UserProfile/Presenter/UserProfilePresenter.swift, EmbeddedSocialTests/Modules/UserProfile/Mocks/MockUserProfileInteractor.swift, EmbeddedSocialTests/Modules/UserProfile/UserProfilePresenterTests.swift
=> #692 - [Manual] - Incorrect list of actions for user in offline mode - Implemented

EmbeddedSocial/Sources/Model/CrossModuleCoordinator.swift
=> #688 - [Manual] - No default list of suggested users for "People" tab on "Search" screen - Implemented

EmbeddedSocial/Sources/Modules/FeedModule/Interactor/FeedModuleInteractor.swift, EmbeddedSocial/Sources/Modules/FeedModule/Presenter/FeedModulePresenter.swift, EmbeddedSocial/Sources/Modules/PostDetail/Presenter/PostDetailPresenter.swift, EmbeddedSocialTests/Modules/FeedModule/FeedModuleInteractor-SocialActions-Tests.swift, EmbeddedSocialTests/Modules/FeedModule/FeedModuleInteractor-Tests.swift, EmbeddedSocialTests/Modules/FeedModule/FeedModulePresenterTests.swift
=> #723 - [Manual] - Previous search results from cache are displayed in offline mode for a new search request - Implemented

EmbeddedSocial/Sources/Modules/SearchPeople/Interactor/SearchPeopleInteractor.swift, EmbeddedSocialTests/Modules/SearchPeople/SearchPeopleInteractorTests.swift
=> #731 - [Manual] - The "Based on who you follow" section header disappears after following or unfollowing user on "Search" screen - Implemented

EmbeddedSocial/Sources/Model/Entities/User.swift, EmbeddedSocial/Sources/Model/Services/UserService.swift, EmbeddedSocial/Sources/Utils/PaginatedResponse.swift
=> #740 - User profile crashes when null userHandle is returned from API - Implemented

EmbeddedSocial/Sources/Modules/LinkedAccounts/View/LinkedAccounts.storyboard
=> #742 - [Manual] - Switchers are disabled on "Linked accounts" screen after an attempt to turn off all accounts - Implemented

EmbeddedSocial/Sources/Common/PaginatedListProcessor/AbstractPaginatedListProcessor.swift, EmbeddedSocial/Sources/Common/PaginatedListProcessor/PaginatedListProcessor.swift, EmbeddedSocial/Sources/Modules/LinkedAccounts/View/LinkedAccounts.storyboard, EmbeddedSocial/Sources/Modules/SearchPeople/Presenter/SearchPeoplePresenter.swift, EmbeddedSocial/Sources/Modules/UserList/Interactor/UserListInteractor.swift, EmbeddedSocial/Sources/Modules/UserList/Interactor/UserListInteractorInput.swift, EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListModuleInput.swift, EmbeddedSocial/Sources/Modules/UserList/Presenter/UserListPresenter.swift, EmbeddedSocialTests/Mocks/MockUserListModuleInput.swift, EmbeddedSocialTests/Modules/SearchPeople/SearchPeoplePresenterTests.swift, EmbeddedSocialTests/Modules/UserList/Mocks/MockUserListInteractor.swift, EmbeddedSocialTests/Modules/UserList/UserListPresenterTests.swift
=> #745 - [Manual] - Previous search results from cache are displayed in offline mode for a new people search request - Implemented

EmbeddedSocial/Sources/Modules/FeedModule/Presenter/FeedModulePresenter.swift, EmbeddedSocial/Sources/Modules/FeedModule/View/FeedModuleViewController.swift, EmbeddedSocial/Sources/Modules/FeedModule/View/FeedModuleViewOutput.swift, EmbeddedSocial/Sources/Modules/PostDetail/Presenter/PostDetailPresenter.swift
=> Error message temporarily flashes on screen - Fixed
